# Copyright Hans Dembinski 2016-2017
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

sudo: false

cache:
  pip: true
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.65.0

language: cpp

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - clang-3.6
      env: COMPILER_VERSION=3.6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - clang-3.8
      env: COMPILER_VERSION=3.8 PYTHON_VERSION=2.7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-4.8
      env: COMPILER_VERSION=4.8
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-7
      env: COMPILER_VERSION=7 CMAKE_BUILD_TYPE=cov

git:
  depth: 1

# Install packages
install:
  - export CXX=${CXX}-${COMPILER_VERSION}
  - export CC=${CC}-${COMPILER_VERSION}

  - BOOST_VERSION=1.65.0 # match version number of cache directory above
  - BOOST_DIR=${TRAVIS_BUILD_DIR}/deps/boost-${BOOST_VERSION}
  - mkdir -p ${BOOST_DIR}
  - |
    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
      pip install --user numpy==1.11.1
      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
      { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
      (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 install --prefix=${BOOST_DIR})
    fi

  - if [ -z ${PYTHON_VERSION} ]; then
      export BUILD_PYTHON=OFF;
    else
      export BUILD_PYTHON=ON;
    fi
  - if [ -z ${NUMPY_SUPPORT} ]; then
      export NUMPY_SUPPORT=OFF;
    fi
  - if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then
      pip install --user numpy==1.11.1 cpp-coveralls urllib3[secure];
    fi
  - if [ "${NUMPY_SUPPORT}" = "ON" ]; then
      pip install --user numpy==1.11.1;
    fi

script:
  - cd build
  - if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then

      cmake . -DBOOST_ROOT=${BOOST_DIR}
              -DBUILD_PYTHON=OFF
              -DCMAKE_BUILD_TYPE=cov &&
      make -j2 &&
      ctest -V;
      cmake . -DBOOST_ROOT=${BOOST_DIR}
              -DBUILD_PYTHON=ON
              -DPYTHON_VERSION=2
              -DBUILD_NUMPY_SUPPORT=OFF
              -DCMAKE_BUILD_TYPE=cov &&
      make -j2 &&
      ctest -V;
      cmake . -DBOOST_ROOT=${BOOST_DIR}
              -DBUILD_PYTHON=ON
              -DPYTHON_VERSION=2
              -DBUILD_NUMPY_SUPPORT=ON
              -DCMAKE_BUILD_TYPE=cov &&
      make -j2 &&
      ctest -V;
    else
      cmake . -DBOOST_ROOT=${BOOST_DIR}
              -DBUILD_PYTHON=${BUILD_PYTHON}
              -DPYTHON_VERSION=${PYTHON_VERSION}
              -DBUILD_NUMPY_SUPPORT=${NUMPY_SUPPORT}
              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} &&
      make -j2 &&
      ctest -V;
    fi

# Calculate coverage
after_success:
  if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then
    coveralls -r .. -b . --verbose --exclude ${TRAVIS_BUILD_DIR}/deps  --gcov=`which gcov-${COMPILER_VERSION}` --gcov-options '\-lp';
  fi

after_failure:
  # - printf "r\nbt" > gdb.cmd
  # - for x in *_test; do
  #     $x || gdb $x --batch -x gdb.cmd;
  #   done

notifications:
  email: false
